// 1. Citation Generator Logic
function generateCitation() {
    const tool = document.getElementById('aiTool').value;
    const version = document.getElementById('aiVersion').value;
    const year = new Date().getFullYear();
    const resultBox = document.getElementById('resultBox');
    const output = document.getElementById('citationOutput');

    if (tool === "" || version === "") {
        alert("Please fill in both the AI Tool and the Version fields.");
        return;
    }

    const citation = `${tool}. (${year}). ${tool} (${version}) [Large language model]. https://chat.openai.com`;
    output.innerText = citation;
    resultBox.style.display = "block";
}

function copyCitation() {
    const text = document.getElementById('citationOutput').innerText;
    navigator.clipboard.writeText(text).then(() => {
        alert("Citation copied to clipboard!");
    });
}

// 2. Disclosure Statement Builder Logic
function buildStatement() {
    const type = document.getElementById('usageType').value;
    let statement = "";
    
    if(type === "brainstorming") {
        statement = "I acknowledge the use of Generative AI for brainstorming and structuring this assignment. All final content, analysis, and writing is my original work.";
    } else if(type === "drafting") {
        statement = "I acknowledge the use of Generative AI to assist in drafting specific sections of this paper. The AI-generated output was heavily reviewed, edited, and fact-checked for accuracy and personal voice.";
    } else {
        statement = "I acknowledge the use of AI-driven editing tools for refining grammar, punctuation, and style. No original ideas or core arguments were generated by AI.";
    }
    
    document.getElementById('statementResult').innerHTML = `<strong>Copy this statement:</strong><br><br><code>${statement}</code>`;
}

// 3. Integrity Self-Audit Logic
function checkIntegrity() {
    const factCheck = document.getElementById('check1').checked;
    const ownVoice = document.getElementById('check2').checked;
    const result = document.getElementById('auditResult');

    if(factCheck && ownVoice) {
        result.innerHTML = "<span style='color:#2ecc71; font-weight:bold;'>✅ Status: Safe (Green/Yellow Zone).</span><br>You are following SBBU Academic Integrity guidelines.";
    } else if (factCheck || ownVoice) {
        result.innerHTML = "<span style='color:#f1c40f; font-weight:bold;'>⚠️ Status: Warning (Yellow Zone).</span><br>You are missing a crucial step. Ensure you have fact-checked everything AND that the final text is in your own words before submitting.";
    } else {
        result.innerHTML = "<span style='color:#e74c3c; font-weight:bold;'>❌ Status: Danger (Red Zone).</span><br>Do not submit! Submitting unchecked AI text that isn't in your own voice is considered plagiarism under university policy.";
    }
}

// 4. Hybrid AI Detection Engine (Cloud API + Offline Fallback)
async function scanDocument() {
    const text = document.getElementById('documentText').value;
    const reportBox = document.getElementById('scanReport');
    
    if (text.trim() === "") {
        alert("Please paste the assignment text to run the scan.");
        return;
    }

    reportBox.style.display = "block";
    reportBox.innerHTML = `
        <div style="text-align:center; padding: 30px;">
            <h3 style="color: #003366;">Scanning document... ⏳</h3>
            <p style="color: #666; font-size: 14px;">Connecting to Cloud AI...</p>
        </div>
    `;

    let aiScore = 0;
    let scanType = "Cloud Neural Network";

    try {
        // Attempt 1: Direct Hugging Face Cloud API
        const API_URL = "https://api-inference.huggingface.co/models/roberta-base-openai-detector";
        const API_KEY = "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";

        const response = await fetch(API_URL, {
            method: 'POST',
            headers: {
                'Authorization': `Bearer ${API_KEY}`,
                'Content-Type': 'application/json'
            },
            body: JSON.stringify({ inputs: text })
        });

        if (!response.ok) throw new Error("Cloud API Blocked");
        
        const result = await response.json();
        
        if (result.error && result.error.includes("loading")) {
             throw new Error("Model Cold Start");
        }

        const fakeData = result[0].find(p => p.label === "Fake");
        if (fakeData) aiScore = (fakeData.score * 100).toFixed(1);

    } catch (error) {
        // Attempt 2: Auto-Fallback to Local Offline Algorithm if internet/API fails
        scanType = "Offline Algorithmic Fallback";
        
        const lowerText = text.toLowerCase();
        const sentences = text.match(/[^.!?]+[.!?]+/g) || [text];
        let sentenceLengths = sentences.map(s => s.trim().split(/\s+/).length).filter(l => l > 0);
        let totalWords = sentenceLengths.reduce((a, b) => a + b, 0);
        let avgLength = totalWords / sentenceLengths.length;
        let variance = sentenceLengths.reduce((a, b) => a + Math.pow(b - avgLength, 2), 0) / sentenceLengths.length;
        let standardDeviation = Math.sqrt(variance);
        
        let burstinessScore = 0;
        if (standardDeviation < 3.5) burstinessScore = 75; 
        else if (standardDeviation < 5.5) burstinessScore = 55; 
        else if (standardDeviation < 8.0) burstinessScore = 25; 
        else burstinessScore = 5; 

        const aiBuzzwords = ["delve", "tapestry", "multifaceted", "crucial", "underscore", "robust", "additionally", "furthermore", "essential"];
        let aiWordHits = 0;
        aiBuzzwords.forEach(word => {
            const regex = new RegExp("\\b" + word + "\\b", "g");
            const matches = lowerText.match(regex);
            if (matches) aiWordHits += matches.length;
        });

        let lexicalDensity = (aiWordHits / (totalWords || 1)) * 100;
        let lexicalScore = lexicalDensity > 2.0 ? 20 : (lexicalDensity > 1.0 ? 10 : 0);

        aiScore = burstinessScore + lexicalScore;
        if (aiScore > 98) aiScore = 98;
    }

    // 5. Check for Institutional Policy Compliance
    const hasDisclosure = text.toLowerCase().includes("acknowledge the use") || text.toLowerCase().includes("generative ai");
    let disclosureHTML = hasDisclosure 
        ? "<span style='color: #2ecc71; font-weight: bold;'>✅ Policy Met:</span> Disclosure Statement detected." 
        : "<span style='color: #e74c3c; font-weight: bold;'>❌ Policy Violation:</span> No AI Disclosure found. (Requires manual faculty review)";

    // 6. Render Final Dashboard
    let riskColor, riskText;
    if (aiScore >= 65) {
        riskColor = "#e74c3c"; 
        riskText = "Highly Likely AI-Generated";
    } else if (aiScore >= 35) {
        riskColor = "#f39c12"; 
        riskText = "Contains Mix of Human and AI Text";
    } else {
        riskColor = "#2ecc71"; 
        riskText = "Highly Likely Human-Written";
    }

    reportBox.innerHTML = `
        <div style="text-align: center; margin-bottom: 20px;">
            <h1 style="font-size: 48px; color: ${riskColor}; margin: 0;">${aiScore}%</h1>
            <h3 style="color: ${riskColor}; margin-top: 5px; text-transform: uppercase;">${riskText}</h3>
        </div>
        
        <div style="background: #f8f9fa; padding: 15px; border-radius: 8px; margin-bottom: 15px; text-align: left;">
            <h4 style="margin-bottom: 10px; color: #333;">System Diagnostic Data</h4>
            <p style="font-size: 14px; margin-bottom: 5px;"><strong>Engine Used:</strong> ${scanType}</p>
            <p style="font-size: 14px; margin-bottom: 5px;"><strong>Status:</strong> Success (System stable)</p>
        </div>

        <div style="border-top: 1px solid #ddd; padding-top: 15px; text-align: left;">
            <p>${disclosureHTML}</p>
        </div>
    `;
}
